### ISSUE TITLE
Action failing on Mac due to known DNS GH problem

### ISSUE THREAD

**Issue by squakez** [container-tools/kind-action#19]
Kind with registry may have problem on macos runners due to DNS (see https://github.com/actions/runner-images/issues/8649).

**Comment by squakez** [comment]
The workaround for the time being is to change the `kind-registry` host name with `127.0.0.1` as done in https://github.com/apache/camel-k/pull/5076/commits/ee547143d906771edc0a6cba42314ecd78238c12

**Comment by gansheer** [comment]
Fixed by https://github.com/container-tools/kind-action/pull/23.
